# Generated by Django 4.1.2 on 2023-10-23 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieIndutry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('youtube_url', models.URLField(max_length=400)),
                ('website_url', models.URLField(max_length=400)),
                ('owner', models.CharField(max_length=200)),
                ('industry_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry', to='api.movieindutry')),
            ],
        ),
    ]
