# Generated by Django 4.1.2 on 2023-10-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_productionhouse_youtube_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionhouse',
            name='website_url',
            field=models.URLField(max_length=400, null=True),
        ),
    ]
